(() => {
 'use strict';
 const C=CenterCore,$=s=>document.querySelector(s),KEY='agent-center-standard-v1';
 const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paths={shield:'M12 3 3 7v6c0 5 9 9 9 9s9-4 9-9V7l-9-4z M8 12l3 3 5-6',studio:'M3 4h18v16H3z M3 9h18 M8 9v11',package:'m12 3 9 5v9l-9 5-9-5V8l9-5z M3 8l9 5 9-5 M12 13v9 M8 5l9 5',runtime:'M3 4h18v12H3z M8 21h8 M12 16v5 M8 8l3 2-3 2 M14 12h3',file:'M5 3h9l5 5v13H5z M14 3v6h5 M8 13h8 M8 17h6',plus:'M12 5v14 M5 12h14',arrow:'M5 12h14 M14 7l5 5-5 5',download:'M12 3v13 M7 11l5 5 5-5 M4 17v4h16v-4',upload:'M12 16V3 M7 8l5-5 5 5 M4 16v5h16v-5',model:'M4 19V9 M10 19V5 M16 19v-7 M22 19H2 M16 5h5v5 M15 11l6-6',case:'M9 3h6l2 3h4v15H3V6h4l2-3z M9 3v5h6V3 M7 12h10 M7 16h7',check:'M5 12l4 4L20 5',close:'M6 6l12 12 M18 6 6 18',settings:'M4 6h16 M4 12h16 M4 18h16 M8 3v6 M16 9v6 M10 15v6',history:'M3 11a9 9 0 1 1 2 7 M3 4v7h7 M12 7v6l4 2',play:'m8 4 12 8-12 8z',info:'M12 16v-5 M12 7h.01 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0'};
 const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.file}"/></svg>`;
 const btn=(text,action,cls='',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
 const label=(text,color='')=>`<span class="pill ${color}">${h(text)}</span>`;
 let db={projects:C.copy(CenterSeed.projects),agents:[],library:C.copy(CenterLibrary),reports:{},packages:[],instances:[]},loadWarning='';
 try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s){if(!Array.isArray(s.projects)||!s.projects.length||!Array.isArray(s.agents)||!Array.isArray(s.packages)||!Array.isArray(s.instances)||!s.reports)throw Error('invalid');s.agents.forEach(C.validateDefinition);db=s;}}catch(e){loadWarning='本地数据无法读取，当前显示默认配置；保存新内容前请先备份原有浏览器数据。';}
 if(!db.library)db.library=C.copy(CenterLibrary);
 // 仅补齐不存在的预置项；已有智能体、公共资源、评测和交付记录保持不变。
 const presetAdded=!loadWarning && CenterPresets.seedMissing(db);
 if(presetAdded){try{localStorage.setItem(KEY,JSON.stringify(db));}catch(e){loadWarning='预置智能体已显示，但浏览器存储不可用；刷新前请导出需要保留的配置。';}}

 const initialView=new URLSearchParams(location.search).get('view');
 const state={view:['studio','library','packages'].includes(initialView)?initialView:'studio',projectId:db.projects[0].id,agentId:null,section:'basic',draft:null,dirty:false,isNew:false,libraryGroup:'skills',wizard:null,wizardStep:0,upgradeId:null,inspectPackage:null,busy:false};
 const sections=[['basic','基本信息'],['role','身份与角色'],['prompt','提示词'],['skills','Skill 技能'],['workflow','Workflow 流程'],['knowledge','RAG 知识'],['memory','记忆策略'],['tools','Tool 工具'],['mcp','MCP'],['model','模型设置'],['permissions','权限范围'],['output','输出规范'],['tests','测试用例'],['evaluation','发布检查'],['version','版本管理'],['package','打包交付']];
 const key=a=>a.projectId+'/'+a.id,project=()=>db.projects.find(p=>p.id===state.projectId),agents=()=>db.agents.filter(a=>a.projectId===state.projectId),packages=()=>db.packages.filter(p=>p.projectId===state.projectId),instances=()=>db.instances.filter(i=>i.projectId===state.projectId);
 function save(){try{localStorage.setItem(KEY,JSON.stringify(db));return true;}catch(e){toast('浏览器存储不可用或已满，请导出当前交付包；本次数据仅在当前页面保留。');return false;}}
 let toastTimer;
 function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4500);}
 const now=()=>new Date().toISOString();
 const date=t=>t?new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'尚未验证';
 const aiIcon=a=>`<span class="agent-icon ${a.id==='case-analyst'?'teal':''}">${icon(a.id==='case-analyst'?'case':'model')}</span>`;
 function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function header(title,subtitle,actions=''){return `<div class="center-head"><div><div class="eyebrow">AGENT CENTER</div><h1>${title}</h1><p>${subtitle}</p></div><div class="actions">${actions}</div></div>`;}
 const journey=()=>`<div class="journey">${[['01','智能体开发','角色 · 逻辑 · 能力资源'],['02','调试与验证','测试用例 · 发布检查'],['03','版本打包','完整定义 · 标准依赖'],['04','导出与交付','接收方登记 · 交付记录']].map(([n,t,d])=>`<div class="journey-item"><span class="journey-num">${n}</span><div><strong>${t}</strong><small>${d}</small></div></div>`).join('')}</div>`;
 function render(){
   const p=project(),active=state.view==='editor'?'studio':state.view;
   $('#app').innerHTML=`<div class="embedded-center"><div class="workspace"><header class="workspace-toolbar"><span>开发空间</span><div class="top-actions"><select class="project-switch" id="project-select" aria-label="当前开发空间">${db.projects.map(x=>`<option value="${h(x.id)}" ${x.id===p.id?'selected':''}>${h(x.name)}</option>`).join('')}</select></div></header><main class="main">${loadWarning?`<div class="banner">${h(loadWarning)}</div>`:''}${state.view==='studio'?studio():state.view==='editor'?editor():state.view==='library'?libraryPage():packagePage()}<div class="local-disclosure">当前为原型：资源调用为 Mock，配置与交付记录保存在本浏览器；不采集客户现场数据。</div></main></div></div>`;
   if(!hostNavigating) parent.postMessage({channel:'fanzha-agent-center',type:'view',view:active},location.origin);
 }
 function studio(){const p=project(),list=agents();return `${header('智能体工作台','面向反诈产品部，完成智能体配置、验证与交付；客户现场私有化运行，数据不回传。',btn('开发空间管理','projects'))}<div class="project-overview"><div class="project-card"><div class="project-mark">${h(p.code)}</div><div><h2>${h(p.name)}</h2><p>${h(p.background)}</p><div class="heading-meta"><span>${h(p.id)}</span><span>·</span><span>${h(p.owner)}</span></div></div></div><div class="project-stats"><div><strong>${list.length}</strong><span>本空间智能体</span></div><div><strong>${packages().length}</strong><span>交付包</span></div><div><strong>${packages().filter(p=>p.delivered).length}</strong><span>已登记交付包</span></div></div></div><div class="section-head"><h2>我的智能体 <span class="note">${list.length} 个</span></h2><span class="note">新建 → 选择能力 → 配置参数 → 完成创建</span></div><div class="agent-home-grid">${list.map(a=>{const r=db.reports[key(a)];return `<section class="panel created-agent"><div class="panel-body"><div class="package-meta">${aiIcon(a)}${label(r?.passed?'原型检查通过':'已创建',r?.passed?'green':'')}</div><h2>${h(a.name)}</h2><p>${h(a.goal)}</p><div class="tags"><span class="tag">${a.skills.length} Skills</span><span class="tag">${a.mcp.length} MCP</span><span class="tag">${a.knowledge.length} 知识资源</span></div><div class="package-detail">v${h(a.version)} · ${h(p.name)}</div></div><div class="config-bottom">${btn(icon('settings')+'参数配置','open-agent','small',`data-id="${h(a.id)}"`)}${btn('验证与交付 '+icon('arrow'),'agent-delivery','small',`data-id="${h(a.id)}"`)}</div></section>`;}).join('')}<button class="new-agent-card" data-action="new-agent"><span class="new-agent-plus">${icon('plus')}</span><strong>新建智能体</strong><span>设置身份与目标，选择通用能力资源<br>配置完成后可打包交付使用</span></button></div><div class="project-tip"><div class="tip-card">${icon('settings')}<div><h3>能力资源统一管理</h3><p>Skill、MCP、Workflow、RAG 和 Tool 可独立维护，新建或编辑智能体时直接选择，不重复填写。</p>${btn('查看通用资源 '+icon('arrow'),'nav','ghost small','data-view="library"')}</div></div><div class="tip-card">${icon('package')}<div><h3>成熟后再打包交付</h3><p>配置与验证完成后，生成交付包。交付包用于项目侧适配与私有化部署；现场模型、数据连接及运行验证由项目侧完成。</p></div></div></div>`;}
 function openAgent(id){const a=agents().find(x=>x.id===id);if(!a)return;state.isNew=false;state.agentId=id;state.draft=C.copy(a);state.section='basic';state.view='editor';state.dirty=false;render();}
 function collectDraft(){
   if(!state.draft)return;
   document.querySelectorAll('[data-prop]').forEach(el=>{const prop=el.dataset.prop;let value=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;
     if(prop.includes('.')){const [parent,k]=prop.split('.');state.draft[parent][k]=value;}else state.draft[prop]=value;});
   const j=$('#json-editor');if(j){state.draft[j.dataset.group]=JSON.parse(j.value);}
 }
 function saveDraft(){collectDraft();const cleaned=C.cleanDefinition(state.draft);const ix=db.agents.findIndex(a=>key(a)===key(cleaned));if(ix<0)db.agents.push(cleaned);else db.agents[ix]=cleaned;delete db.reports[key(cleaned)];state.draft=C.copy(cleaned);state.dirty=false;save();return cleaned;}
 const textField=(title,prop,value,area=false,extra='')=>`<div class="field ${area?'full':''}"><label for="field-${h(prop)}">${h(title)}</label>${area?`<textarea id="field-${h(prop)}" data-prop="${h(prop)}" ${extra}>${h(value)}</textarea>`:`<input id="field-${h(prop)}" data-prop="${h(prop)}" value="${h(value)}" ${extra}>`}</div>`;
 const jsonEditor=(group,info)=>`<p class="editor-note">${info}</p><label class="field"><span>${h(sections.find(x=>x[0]===group)?.[1]||group)} 配置</span><textarea class="code" id="json-editor" data-group="${group}" spellcheck="false">${h(C.json(state.draft[group]))}</textarea></label>`;
 function editor(){const a=state.draft,r=db.reports[key(a)],title=sections.find(x=>x[0]===state.section)[1];return `${header(state.isNew?'新建智能体':h(a.name),'配置通用能力、调试与验证，通过后形成不可变交付版本。',btn('返回工作台','nav','','data-view="studio"')+btn(state.isNew?'完成创建':'保存参数',state.isNew?'finish-create':'save-draft','primary'))}<div class="heading-meta" style="margin:-12px 0 21px">${label(project().name)}<span class="version-tag">v${h(a.version)}</span>${state.dirty?label('未保存修改','amber'):label('本地草稿','gray')}<span>正式接入与效果验证待完成</span></div><div class="editor-layout"><aside class="edit-menu"><p>AGENT DEFINITION</p>${sections.map(([id,name],i)=>btn(`<span>${String(i+1).padStart(2,'0')}</span>${name}`,'section',state.section===id?'active':'',`data-section="${id}"`)).join('')}</aside><section class="panel editor-surface"><div class="panel-head"><h2>${title}</h2><span class="note">${h(a.id)}</span></div><div class="panel-body">${a.id==='model-optimizer' && state.section==='basic'?"<div class=\"editor-note\"><strong>模型优化接入参考（尚未连接）</strong><p>输入：模型 SQL、账期、字段映射、涉诈标签表、预测结果表和特征数据源。现场流程：基线评估 → 漏报分析 → SQL 条件调整 → 回测对比 → 人工确认。</p><p>输出：候选 SQL、规则修改建议、条件差异及有样本依据的 F1 / 命中数量对比。当前参考代码最多回测 5 轮；未提升不等于已证明最优。现场数据和指标不回传本平台。</p></div>":''}${editorBody(a,r)}</div><div class="editor-actions"><span class="note">任何配置修改都需要重新验证，旧评测不会批准新内容。</span><div class="actions">${btn('调试与验证','section','','data-section="evaluation"')}${btn(icon('package')+'发布检查与打包','section','primary','data-section="package"')}</div></div></section></div>`;}
 function editorBody(a,r){
   const s=state.section;
   if(['skills','workflow','knowledge','tools','mcp'].includes(s))return resourcePicker(s==='workflow'?'workflows':s);
   if(state.isNew&&['tests','evaluation','version','package'].includes(s))return '<div class="banner blue">请先完成基本信息与能力选择，点击右上角“完成创建”，再进行测试和交付。</div>'; 
   if(s==='basic')return `<div class="form-grid">${state.isNew?textField('智能体标识','id',a.id):''}${textField('智能体名称','name',a.name)}${textField('版本号','version',a.version)}${textField('业务目标','goal',a.goal,true)}${textField('适用背景','background',a.background,true)}</div>`;
   if(s==='role')return `${textField('身份、职责、边界与禁止事项','role',a.role,true)}<p class="editor-note" style="margin-top:16px">岗位身份与任务权限分开。Role 不自动授予现场操作权限。</p>`;
   if(s==='prompt')return `${textField('System Prompt','prompt',a.prompt,true,'style="min-height:310px"')}<p class="editor-note" style="margin-top:16px">随交付包导出。不要填写真实密钥、客户账号或现场敏感数据。</p>`;
   if(s==='skills')return jsonEditor('skills','Skill 包含独立 ID、版本、内容，可随包交付。项目现场不需要预先安装同名 Skill，只需具备兼容 Skill Runtime。');
   if(s==='workflow')return `<div class="workflow-canvas">${a.workflow.map(n=>`<div class="flow-node ${n.type}"><span class="node-icon">${icon(n.type==='human'?'check':n.type==='tool'?'settings':'studio')}</span><div><strong>${h(n.title)}</strong><small>${h(n.target||'人工确认')} · 超时 ${n.timeout}s · 重试 ${n.retry} 次</small></div>${label(n.type==='human'?'人工确认':n.type==='tool'?'Tool':'Skill',n.type==='human'?'amber':'')}</div>`).join('')}</div><p class="editor-note" style="margin-top:15px">MVP 支持顺序调用、人工确认、有限重试和超时。分支、循环及 Agent 调用属于后续运行时能力。</p>${jsonEditor('workflow','编辑下方节点定义，保存时校验 Skill 与 Tool 引用。')}`;
   if(s==='knowledge')return `${a.knowledge.map(k=>`<div class="config-resource"><div class="resource-head"><h3>${h(k.name)}</h3>${label(k.mode==='package'?'随包知识':'现场绑定',k.mode==='package'?'green':'amber')}</div><p class="note">${k.mode==='package'?'正文随包交付，须具备 approved 标记。':'只打包需求，真实知识库在现场关联，不打包现场数据。'}</p></div>`).join('')}${jsonEditor('knowledge','package 必须包含 content 与 approved；runtime 只能声明 id、name 和 mode。')}`;
   if(s==='memory')return `<div class="form-grid"><div class="field"><label for="memory-mode">记忆策略</label><select id="memory-mode" data-prop="memory.mode">${[['none','关闭'],['task','任务记忆'],['session','会话记忆'],['project','项目记忆（预留）']].map(([v,n])=>`<option value="${v}" ${a.memory.mode===v?'selected':''}>${n}</option>`).join('')}</select></div>${textField('保留天数','memory.retentionDays',a.memory.retentionDays,false,'type="number" min="0"')}</div><div class="banner blue" style="margin-top:20px">只交付记忆策略，不交付运行期记忆。实际 Memory 服务尚未接入。</div>`;
   if(s==='tools')return jsonEditor('tools','声明标准工具能力与输入输出 Schema。现场数据库、接口或脚本通过适配器实现，不把连接地址写入智能体定义。');
   if(s==='mcp')return `${jsonEditor('mcp','只声明连接能力与所需工具；项目侧绑定实际 MCP Server。')}<div class="field" style="margin-top:20px"><label for="secret-refs">Secret 引用名称（逗号分隔）</label><input id="secret-refs" value="${h(a.secretRefs.join(', '))}"><span class="note">只接受引用名称，如 PROJECT_FILE_TOKEN，禁止填写实际值。</span></div>`;
   if(s==='model')return `<div class="form-grid">${textField('偏好模型或模型服务','model.preferred',a.model.preferred)}${textField('最低上下文长度','model.minContext',a.model.minContext,false,'type="number" min="1024" max="2000000"')}</div><h3 style="margin-top:25px">最低能力要求</h3><div class="check-box-area">${[['chinese','中文能力'],['toolCalling','Tool Calling'],['structuredOutput','结构化输出'],['jsonSchema','JSON Schema'],['multiTurn','多轮任务']].map(([id,n])=>`<label class="check-label"><input type="checkbox" data-prop="model.${id}" ${a.model[id]?'checked':''}>${n}</label>`).join('')}</div><p class="editor-note" style="margin-top:17px">现场通过能力而非厂商名称适配模型。当前要求不是已验证的现场模型能力。</p>`;
   if(s==='permissions')return jsonEditor('permissions','只声明所需权限，不随包直接赋予。highImpact 标记修改、删除、批量操作及外部写入等高影响权限。');
   if(s==='output')return `${textField('输出文档模板','output',a.output,true,'class="code"')}<p class="editor-note" style="margin-top:15px">模板随包交付；正式服务还需验证结构、事实与证据引用。</p>`;
   if(s==='tests')return `${a.tests.map((t,i)=>`<div class="test-case"><strong>用例 ${String(i+1).padStart(2,'0')} · ${h(t.id)}</strong><p>${h(t.input)}</p><small>验证要求：${h(t.expected)}</small></div>`).join('')}<div style="margin-top:20px">${jsonEditor('tests','管理测试输入与预期结果。本地原型不调用内网模型，不自动生成效果评分。')}</div>`;
   if(s==='evaluation')return `<div class="banner">这里只执行真实的结构检查和演示评分门禁，不等同于模型效果评测。</div>${renderChecks(C.structuralChecks(a))}<div class="test-controls">${textField('最低人工评分','evaluation.minScore',a.evaluation.minScore,false,'type="number" min="0" max="100"')}<div class="field"><label for="manual-score">本次演示评分</label><input id="manual-score" type="number" min="0" max="100" value="${r?.score??85}"></div></div><label class="check-label"><input id="review-confirm" type="checkbox">我已核对本次原型配置，确认仅用于设计评审</label><div class="actions" style="margin-top:20px">${btn(icon('check')+'运行原型发布检查','evaluate','primary')}</div>${r?`<div class="${r.passed?'success-box':'error-box'}" style="margin-top:20px">${r.passed?'检查通过':'检查未通过'} · ${date(r.time)} · 人工演示评分 ${r.score} / 100<br>定义摘要 ${h(r.definitionDigest.slice(0,22))}…</div>`:''}`;
   if(s==='version')return `<p class="editor-note">同一项目、Agent、版本不可覆盖打包。修改后保存新版本，重新检查再交付。</p>${textField('下一个交付版本','version',a.version)}${packages().filter(p=>p.agentId===a.id).map(p=>`<div class="version-line"><div><strong>v${h(p.version)}</strong><div class="note">${date(p.created)} · 已冻结为原型交付包</div></div>${btn('查看清单','inspect-package','small',`data-id="${h(p.id)}"`)}</div>`).join('')||'<div class="empty"><h3>尚无已打包版本</h3><p>完成验证后，在 Package 页面生成首个版本。</p></div>'}`;
   if(s==='package')return `<div class="banner blue">原型 .agent 文件采用 JSON 容器，包含完整文件映射与 SHA-256 摘要。正式生产包采用 ZIP 与可信签名，详见设计方案。</div>${renderChecks(C.structuralChecks(a))}<div class="dependency-summary"><span class="dependency-count"><strong>${a.skills.length}</strong>Skill</span><span class="dependency-count"><strong>${a.tools.length}</strong>Tool 契约</span><span class="dependency-count"><strong>${a.knowledge.filter(k=>k.mode==='runtime').length}</strong>现场知识依赖</span></div><p class="review-summary">${r?.passed?'已有原型检查记录。打包时会重新比对定义摘要，配置变更将被阻止。':'尚未通过当前配置的原型发布检查。请先进入 Evaluation 完成核对。'}</p><div class="actions">${btn('去验证','section','','data-section="evaluation"')}${btn(icon('package')+'生成原型交付包','build-package','primary',state.busy?'disabled':'')}</div>`;
   return '';
 }
 function renderChecks(checks){return `<div class="checks">${checks.map(c=>`<div class="check-row ${c.status}"><span class="status-icon">${c.status==='pass'?'✓':c.status==='blocked'?'×':'!'}</span><span>${h(c.name)}</span><small>${h(c.detail)}</small>${label({pass:'通过',blocked:'阻断',binding:'待绑定',warning:'提示'}[c.status],c.status==='pass'?'green':c.status==='blocked'?'red':'amber')}</div>`).join('')}</div>`;}
 function packagePage(){const list=packages();return `${header('交付包管理','完整定义随包交付，现场只做环境适配。',btn('返回智能体工作台','nav','','data-view="studio"'))}${journey()}<div class="center-layout-note">包内容与版本冻结；Secret 值、现场地址和运行期 Memory 不进入包。原型摘要校验不等于发布签名。</div>${list.length?`<div class="package-grid">${list.slice().reverse().map(p=>`<section class="panel package-card"><div class="panel-body"><div class="package-meta"><span class="package-icon">${icon('package')}</span>${label('原型包','amber')}</div><h3>${h(p.name)}</h3><div class="package-detail">${h(project().name)} · <span class="version-tag">v${h(p.version)}</span><br>${date(p.created)} · ${Object.keys(p.payload.files).length} 个文件<br>${h(p.delivered?'已登记交付':'待交付')}${(p.deliveries||[]).map(d=>`<br>交付对象：${h(d.recipient)} · ${date(d.time)}`).join('')}</div><div class="package-hash">SHA-256 ${h(p.payload.packageDigest)}</div><div class="actions">${btn('清单','inspect-package','small',`data-id="${h(p.id)}"`)}${btn(icon('download')+'导出 .agent','export-package','small',`data-id="${h(p.id)}"`)}${btn('登记交付','deliver','small',`data-id="${h(p.id)}"`)}</div></div></section>`).join('')}</div>`:`<section class="runtime-empty"><span class="package-icon">${icon('package')}</span><h2>还没有智能体交付包</h2><p>在智能体开发中完成配置与原型发布检查，然后生成交付包。</p>${btn('进入智能体工作台','nav','primary','data-view="studio"')}</section>`}`;}
 function runtimePage(){return state.wizard||state.wizardStep===-1?wizard():`${header('项目运行','接收智能体包，补齐现场绑定，创建开发空间实例。',btn(icon('plus')+'添加智能体','import-start','primary'))}<div class="project-card" style="margin-bottom:23px;padding:17px 22px"><div class="project-mark" style="width:45px;height:48px">${h(project().code)}</div><div><h2 style="font-size:16px">${h(project().name)}运行环境</h2><p>独立内网部署 · 绑定现场模型与系统 · 不重新设计智能体逻辑</p></div></div>${instances().length?instances().map(instanceCard).join(''):`<section class="runtime-empty"><span class="package-icon">${icon('runtime')}</span><h2>添加第一个项目智能体</h2><p>上传 .agent 原型包，查看依赖检查与现场配置流程；本地原型不会启动真实模型或访问项目数据库。</p>${btn(icon('upload')+'上传交付包','import-start','primary')}</section>`}<div class="project-tip"><div class="tip-card">${icon('check')}<div><h3>导入不是重新开发</h3><p>业务逻辑随包导入，现场保留模型、Tool、MCP、知识和权限绑定。</p></div></div><div class="tip-card">${icon('history')}<div><h3>升级与回滚</h3><p>同一 Agent 新版本保留兼容绑定；切换前检查，回滚恢复旧包与绑定快照。</p></div></div></div>`;}
 function wizard(){const w=state.wizard,step=state.wizardStep;
   let body='';
   if(!w){body=`<div class="panel"><div class="panel-body"><div class="upload-package">${icon('upload')}<h3>选择项目智能体交付包</h3><p>当前支持 .agent 原型文件，最大 5 MB；全部在浏览器本地解析。</p>${btn('选择文件','choose-package','primary')}<input id="package-file" type="file" accept=".agent,application/json" class="file-picker" aria-label="上传智能体原型包"></div><h3>或使用本地已生成的交付包</h3>${packages().length?packages().map(p=>`<div class="version-line"><span>${h(p.name)} · v${h(p.version)}</span>${btn('选择并解析','use-package','small',`data-id="${h(p.id)}"`)}</div>`).join(''):'<p class="note">当前开发空间暂无交付包，请先在开发侧完成配置与打包。</p>'}<div id="import-error" class="error-box" hidden></div></div></div>`;}
   else {
     const checks=C.dependencies(w.pkg,w.a,w.bindings,w.env),ready=C.installable(checks);
     body=`<div class="install-layout"><section class="panel"><div class="panel-head"><h2>${step===1?'自动解析与依赖检查':step===2?'现场环境配置':'创建前检查'}</h2>${label('仅现场绑定')}</div><div class="panel-body">${step===2?bindingForm(w):`${step===3?'<div class="banner">将创建本地演示实例，不会启动真实服务。正式安装需服务端鉴权、签名与健康探测。</div>':''}<div class="dependency-summary"><span class="dependency-count"><strong>${checks.filter(c=>c.status==='pass').length}</strong>通过</span><span class="dependency-count"><strong>${checks.filter(c=>c.status==='binding').length}</strong>待绑定</span><span class="dependency-count"><strong>${checks.filter(c=>c.status==='blocked').length}</strong>阻断</span></div>${renderChecks(checks)}`}</div><div class="editor-actions">${btn(step===1?'重新选择文件':'上一步','wizard-back')}<div class="actions">${step<3?btn(step===1?'补齐现场配置':'重新检查','wizard-next','primary'):btn(state.upgradeId?'确认升级演示实例':'创建演示实例','install','primary',!ready?'disabled':'')}</div></div></section><aside class="install-sidebar"><section class="panel"><div class="panel-head"><h2>交付包信息</h2></div><div class="panel-body"><h3>${h(w.a.name)}</h3><div class="package-detail">项目：${h(project().name)}<br>版本：v${h(w.a.version)}<br>${w.a.skills.length} 个 Skill · ${w.a.workflow.length} 个流程节点<br>${w.a.tools.length} 个工具 · ${w.a.mcp.length} 个 MCP 依赖</div><div class="package-hash">${h(w.pkg.packageDigest)}</div><p class="note">角色、Prompt、Skill 与 Workflow 已随包带入，不在现场重写。</p>${state.upgradeId?'<div class="banner blue">升级模式：已保留相同依赖的现场绑定，新增权限需要重新勾选。</div>':''}</div></section></aside></div>`;
   }
   return `${header(state.upgradeId?'升级项目智能体':'添加项目智能体','包解析 → 依赖检查 → 现场绑定 → 创建实例',btn('返回项目运行','import-cancel'))}<ol class="install-steps">${['上传交付包','依赖检查','环境配置','检查与创建'].map((s,i)=>`<li class="${(w?step:0)===i?'active':''}">${i+1}　${s}</li>`).join('')}</ol>${body}`;
 }
 function selectBinding(title,group,id,value,options){return `<div class="field"><label>${h(title)}<select data-bind-group="${group}" data-bind-id="${h(id)}"><option value="">请选择现场资源</option>${options.map(([v,n])=>`<option value="${h(v)}" ${value===v?'selected':''}>${h(n)}</option>`).join('')}</select></label></div>`;}
 function bindingForm(w){const a=w.a,b=w.bindings;return `<div class="banner blue">这里只绑定运行资源，不修改随包逻辑。使用演示资源检验流程，不填写真实密钥。</div><div class="actions" style="margin-bottom:20px">${btn('填入演示资源（不含权限）','fill-bindings','small')}</div><div class="install-form"><h3>模型与平台环境</h3>${selectBinding('大模型服务','root','model',b.model,Object.values(C.profiles).map(m=>[m.id,m.name]))}<div class="field"><label for="environment-case">检查场景</label><select id="environment-case"><option value="ready" ${w.env.compatible&&w.env.network?'selected':''}>模拟内网环境就绪</option><option value="incompatible" ${!w.env.compatible?'selected':''}>模拟 Runtime 不兼容</option><option value="offline" ${!w.env.network?'selected':''}>模拟现场网络不通</option></select></div><h3>工具与 MCP 绑定</h3>${a.tools.map(t=>selectBinding(t.name,'tools',t.id,b.tools[t.id],[['adapter-'+t.id,'项目适配器（演示）']])).join('')}${a.mcp.map(m=>selectBinding(m.name,'mcp',m.id,b.mcp[m.id],[['connection-'+m.id,'内网 MCP 连接（演示）']])).join('')}<h3>项目知识与 Secret 引用</h3>${a.knowledge.filter(k=>k.mode==='runtime').map(k=>selectBinding(k.name,'knowledge',k.id,b.knowledge[k.id],[['kb-'+project().id,'本项目知识库（演示）']])).join('')}${a.secretRefs.map(s=>selectBinding(s,'secrets',s,b.secrets[s],[['secret-ref-'+s,'Secret 服务引用（演示，无实际值）']])).join('')}<h3>开发空间管理员授权（演示）</h3><div class="check-box-area">${a.permissions.map(p=>`<label class="check-label"><input type="checkbox" data-permission="${h(p.id)}" ${b.permissions.includes(p.id)?'checked':''}>${h(p.name)} ${p.highImpact?label('高影响','amber'):''}</label>`).join('')}</div><p class="note" style="margin-top:10px">权限不随包自动授予，未勾选的必需权限会阻止创建。</p></div>`;}
 function instanceCard(i){const rev=i.revisions[i.active],t=i.task;return `<section class="panel instance-card"><div class="panel-body"><div class="instance-head"><div class="namecell">${aiIcon(rev.a)}<div><strong>${h(i.name)}</strong><small>${h(i.id)}</small></div></div><div class="actions">${label(i.status==='running'?'演示运行中':'演示已停止',i.status==='running'?'green':'gray')}${btn(i.status==='running'?'停止':'启动','toggle-instance','small',`data-id="${h(i.id)}"`)}${btn('升级','upgrade-instance','small',`data-id="${h(i.id)}"`)}${btn('回滚','rollback-instance','small',`data-id="${h(i.id)}" ${i.active===0?'disabled':''}`)}</div></div><div class="instance-grid"><div><small>当前包版本</small><strong>v${h(rev.a.version)}</strong></div><div><small>模型绑定</small><strong>${h(C.profiles[rev.bindings.model]?.name||'未绑定')}</strong></div><div><small>健康检查</small><strong>模拟通过 · 非真实探测</strong></div><div><small>实例修订</small><strong>${i.active+1} / ${i.revisions.length}</strong></div></div><div class="actions">${btn(icon('play')+'打开运行台','open-run','small primary',`data-id="${h(i.id)}"`)}</div>${state.runId===i.id?`<div class="runtime-pane"><h3>项目任务运行（演示）</h3><textarea id="run-input" aria-label="任务输入" placeholder="使用虚构输入进行流程演示">${h(t?.input||'')}</textarea><div class="task-actions">${btn('执行演示任务','run-task','primary',`data-id="${h(i.id)}" ${i.status!=='running'||t?.status==='review'?'disabled':''}`)}${t?.status==='review'?btn('确认并继续流程','approve-task','',`data-id="${h(i.id)}"`):''}</div>${t?`<div class="preview-result">${h(t.output)}</div>`:''}</div>`:''}<div class="instance-log">${i.logs.slice(-6).map(l=>`${h(date(l.time))}　${h(l.text)}`).join('<br>')}</div></div></section>`;}
 function designPage(){return `${header('架构与现场部署','标准平台开发智能体，以版本化交付包连接各接收方运行环境。')}<div class="design-grid"><div class="design-block"><span class="package-icon">${icon('studio')}</span><h2 style="margin-top:18px">Agent Studio</h2><p>平台开发侧，配置智能体的角色、逻辑、能力和输出，独立于具体客户。</p><ul><li>开发空间与智能体管理</li><li>16 类定义配置</li><li>调试、验证与版本冻结</li></ul></div><div class="design-block"><span class="package-icon">${icon('package')}</span><h2 style="margin-top:18px">Agent Package</h2><p>交付完整定义及依赖要求，不夹带现场连接和凭据。</p><ul><li>Prompt / Skill / Workflow</li><li>标准工具契约与知识要求</li><li>Manifest、摘要和正式签名</li></ul></div><div class="design-block"><span class="package-icon">${icon('runtime')}</span><h2 style="margin-top:18px">Project Runtime</h2><p>在隔离内网导入，绑定现场资源后实例化运行。</p><ul><li>依赖检查与管理员授权</li><li>模型、MCP、工具与知识适配</li><li>任务、日志、升级和回滚</li></ul></div></div><section class="panel"><div class="panel-head"><h2>标准平台与交付边界</h2>${label('通用能力','blue')}</div><div class="panel-body"><div class="design-steps">${['平台创建并验证智能体','生成版本化智能体包','登记交付对象并导出','接收方导入与绑定资源'].map(t=>`<div>${t}</div>`).join('')}</div><p class="review-summary">平台不预置任何客户专属背景。身份、Skill、Workflow 和输出随智能体定义管理；客户知识库、模型连接、凭据和业务数据在接收方环境绑定。</p><p class="note">开发空间用于团队组织，与客户交付对象分开。项目运行页面用于演示接收方导入流程，当前不会部署到外部环境。</p></div></section>`;}
 function modal(title,body,footer=''){ $('#modal').innerHTML=`<div class="modal-head"><h2>${h(title)}</h2>${btn(icon('close'),'close-modal','ghost','aria-label="关闭"')}</div><div class="modal-body">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}`;$('#modal').showModal();}
 function showProjects(){modal('开发空间管理',db.projects.map(p=>`<div class="project-list-row"><div><h3>${h(p.name)}</h3><span class="note">${h(p.id)} · ${h(p.owner)}</span></div>${btn('进入开发空间','switch-project','small',`data-id="${h(p.id)}"`)}</div>`).join(''),btn('创建开发空间','new-project','primary'));}
 function switchProject(id){if(!canLeave()){render();return;}state.projectId=id;state.view='studio';state.draft=null;state.dirty=false;state.wizard=null;state.wizardStep=0;state.upgradeId=null;state.runId=null;render();}
 async function importPayload(text){const result=await C.parsePackage(text,state.projectId);const prior=state.upgradeId?db.instances.find(i=>i.id===state.upgradeId):null;if(prior){const old=prior.revisions[prior.active];if(result.definition.id!==old.a.id)throw Error('升级包的 Agent 标识不匹配');if(C.compareVersions(result.definition.version,old.a.version)<=0)throw Error('升级版本必须高于当前版本');}state.wizard={pkg:result.pkg,a:result.definition,env:{compatible:true,network:true},bindings:prior?C.preserveBindings(result.definition,prior.revisions[prior.active].bindings):{model:'',tools:{},mcp:{},knowledge:{},permissions:[],secrets:{}}};state.wizardStep=1;state.view='runtime';render();}
 async function action(el){const act=el.dataset.action;
   if(act==='close-modal'){$('#modal').close();return;}
   if(act==='nav'){if(!canLeave())return;if(state.view==='editor'){try{collectDraft();}catch(e){toast('当前 JSON 格式有误，请修正或保存后离开');return;}}state.view=el.dataset.view;state.wizard=null;state.wizardStep=0;render();}
   if(act==='open-agent')openAgent(el.dataset.id);
   if(act==='section'){collectDraft();if($('#secret-refs'))state.draft.secretRefs=$('#secret-refs').value.split(',').map(s=>s.trim()).filter(Boolean);state.section=el.dataset.section;render();}
   if(act==='save-draft'){if($('#secret-refs'))state.draft.secretRefs=$('#secret-refs').value.split(',').map(s=>s.trim()).filter(Boolean);saveDraft();render();toast('草稿已保存，需重新进行原型发布检查');}
   if(act==='projects')showProjects();
   if(act==='switch-project'){$('#modal').close();switchProject(el.dataset.id);}
   if(act==='new-project'){$('#modal').close();modal('创建开发空间','<div class="form-grid"><label class="field">空间名称<input id="new-project-name" placeholder="例如：业务研发空间"></label><label class="field">空间标识<input id="new-project-id" placeholder="例如：business-team"></label><label class="field full">适用背景<textarea id="new-project-background"></textarea></label></div>',btn('保存开发空间','save-project','primary'));}
   if(act==='save-project'){const name=$('#new-project-name').value.trim(),id=$('#new-project-id').value.trim();if(!name||!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(id)||db.projects.some(p=>p.id===id))throw Error('请填写空间名称和未占用的英文标识');db.projects.push({id,name,code:id.slice(0,2).toUpperCase(),owner:'项目组',background:$('#new-project-background').value||'适用背景待补充。'});save();$('#modal').close();switchProject(id);}
   if(act==='new-agent'){const a=CenterSeed.makeAgent(project(),'pm');a.id='agent-'+Date.now().toString(36);a.name='';a.version='0.1.0';a.goal='';a.role='在本项目授权范围内完成分析任务，输出有依据的结论与待核实事项。';a.skills=[];a.workflow=[];a.tools=[];a.mcp=[];a.knowledge=[];a.secretRefs=[];a.resourceRefs=[];state.isNew=true;state.draft=a;state.agentId=a.id;state.section='basic';state.view='editor';state.dirty=false;render();}
   if(act==='finish-create'){collectDraft();const a=C.cleanDefinition(state.draft);if(agents().some(x=>x.id===a.id))throw Error('当前开发空间内已存在此标识');db.agents.push(a);save();state.isNew=false;state.dirty=false;state.view='studio';render();toast('智能体已创建，可进入参数配置继续修改');}
   if(act==='agent-delivery'){openAgent(el.dataset.id);state.section='evaluation';render();}
   if(act==='resource-manager'){state.libraryGroup=el.dataset.group;modal('通用资源管理',`<p>请先保存当前智能体，再进入左侧“能力资源管理”新增或修改资源。</p><p class="note">当前编辑内容保持不变。</p>`);}
   if(act==='library-tab'){state.libraryGroup=el.dataset.group;render();}
   if(act==='resource-new'||act==='resource-edit')openResource(el.dataset.group,el.dataset.id);
   if(act==='save-resource')saveResource();
   if(act==='resource-toggle'){const r=db.library[el.dataset.group].find(x=>x.id===el.dataset.id);r.active=!r.active;save();render();toast(r.active?'资源已启用':'资源已停用，已有智能体快照不受影响');}
   if(act==='save-new-agent'){const a=CenterSeed.makeAgent(project(),$('#new-agent-type').value);a.name=$('#new-agent-name').value.trim();a.id=$('#new-agent-id').value.trim();a.version='0.1.0';C.validateDefinition(a);if(agents().some(x=>x.id===a.id))throw Error('当前开发空间内已存在此标识');db.agents.push(a);save();$('#modal').close();openAgent(a.id);}
   if(act==='evaluate'){collectDraft();if(!$('#review-confirm').checked)throw Error('请先确认已核对原型配置');const score=Number($('#manual-score').value);if(!Number.isFinite(score)||score<0||score>100)throw Error('评分应为 0–100');const a=C.cleanDefinition(state.draft),checks=C.structuralChecks(a),hash=await C.fingerprint(a),pass=checks.every(c=>c.status==='pass')&&score>=a.evaluation.minScore;db.agents=db.agents.map(x=>key(x)===key(a)?a:x);db.reports[key(a)]={mode:'prototype',definitionDigest:hash,score,passed:pass,time:now(),checks};state.draft=C.copy(a);state.dirty=false;save();render();toast(pass?'当前定义通过原型发布检查':'未通过检查，请修正阻断项或评分');}
   if(act==='build-package'){collectDraft();state.busy=true;const a=C.cleanDefinition(state.draft);const payload=await C.buildPackage(a,project(),db.reports[key(a)],db.packages);const p={id:'pkg-'+Date.now().toString(36),projectId:a.projectId,agentId:a.id,name:a.name,version:a.version,created:now(),delivered:false,payload};db.packages.push(p);save();state.view='packages';state.busy=false;render();toast('原型交付包已生成，可导出后在项目侧导入');}
   if(act==='export-package'){const p=db.packages.find(p=>p.id===el.dataset.id);download(`${project().name}-${p.name}-v${p.version}.agent`,C.json(p.payload));toast('已导出原型 .agent 文件');}
   if(act==='inspect-package'){const p=db.packages.find(p=>p.id===el.dataset.id);modal('Agent Manifest 与文件清单',`<div class="banner">原型容器，不是正式 ZIP；摘要验证完整性，不验证发布者身份。</div><pre class="code-block">${h(C.json(p.payload.manifest))}</pre>`);}
   if(act==='deliver'){state.deliveryPackageId=el.dataset.id;modal('登记交付对象','<p class="editor-note">智能体开发与客户交付分开管理。同一版本可以登记多个接收方；登记不会发送文件。</p><label class="field">接收方名称<input id="delivery-recipient" maxlength="80" placeholder="填写客户或接收项目名称"></label>',btn('保存交付记录','save-delivery','primary'));}
   if(act==='save-delivery'){const recipient=$('#delivery-recipient').value.trim();if(!recipient)throw Error('请填写接收方名称');const p=db.packages.find(p=>p.id===state.deliveryPackageId);p.deliveries=p.deliveries||[];p.deliveries.push({recipient,time:now()});p.delivered=true;save();$('#modal').close();render();toast('交付对象已登记，请导出交付包交给接收方；尚未发送或安装');}
   if(act==='import-start'){state.wizard=null;state.wizardStep=-1;state.upgradeId=null;render();}
   if(act==='choose-package')$('#package-file').click();
   if(act==='use-package'){const p=db.packages.find(p=>p.id===el.dataset.id);await importPayload(C.json(p.payload));}
   if(act==='import-cancel'){state.wizard=null;state.wizardStep=0;state.upgradeId=null;render();}
   if(act==='wizard-back'){if(state.wizardStep===1){state.wizard=null;state.wizardStep=-1;}else state.wizardStep--;render();}
   if(act==='wizard-next'){state.wizardStep++;render();}
   if(act==='fill-bindings'){const w=state.wizard;w.bindings={...w.bindings,model:'modern',tools:Object.fromEntries(w.a.tools.map(t=>[t.id,'adapter-'+t.id])),mcp:Object.fromEntries(w.a.mcp.map(t=>[t.id,'connection-'+t.id])),knowledge:Object.fromEntries(w.a.knowledge.filter(k=>k.mode==='runtime').map(k=>[k.id,'kb-'+project().id])),secrets:Object.fromEntries(w.a.secretRefs.map(s=>[s,'secret-ref-'+s]))};render();}
   if(act==='install'){const w=state.wizard,checks=C.dependencies(w.pkg,w.a,w.bindings,w.env);if(!C.installable(checks))throw Error('仍有阻断或待绑定项，不能创建实例');const rev={a:C.copy(w.a),pkg:C.copy(w.pkg),bindings:C.copy(w.bindings),created:now()};if(state.upgradeId){const i=db.instances.find(i=>i.id===state.upgradeId);if(i.task?.status==='review')throw Error('请先完成待确认任务，再升级');i.revisions=i.revisions.slice(0,i.active+1);i.revisions.push(rev);i.active=i.revisions.length-1;i.status='running';i.task=null;i.logs.push({time:now(),text:'模拟升级完成；保留兼容绑定，健康检查模拟通过'});}else{db.instances.push({id:'instance-'+Date.now().toString(36),projectId:project().id,name:w.a.name,revisions:[rev],active:0,status:'running',logs:[{time:now(),text:'依赖结构检查通过；创建本地实例，健康与运行均为模拟'}]});}save();state.wizard=null;state.wizardStep=0;state.upgradeId=null;render();toast('本地演示实例已就绪');}
   if(act==='toggle-instance'){const i=db.instances.find(i=>i.id===el.dataset.id);i.status=i.status==='running'?'stopped':'running';i.logs.push({time:now(),text:i.status==='running'?'演示实例已启动':'演示实例已停止'});save();render();}
   if(act==='upgrade-instance'){state.upgradeId=el.dataset.id;state.wizard=null;state.wizardStep=-1;render();}
   if(act==='rollback-instance'){const i=db.instances.find(i=>i.id===el.dataset.id);if(i.task?.status==='review')throw Error('请先完成待确认任务，再回滚');if(i.active>0){i.active--;i.task=null;i.logs.push({time:now(),text:'已恢复上一修订的包与绑定快照；模拟健康检查通过'});save();render();toast('已回滚到 v'+i.revisions[i.active].a.version);}}
   if(act==='open-run'){state.runId=el.dataset.id;render();}
   if(act==='run-task'){const i=db.instances.find(i=>i.id===el.dataset.id);if(i.status!=='running')throw Error('实例已停止');const input=$('#run-input').value.trim();if(!input)throw Error('请填写任务输入');const a=i.revisions[i.active].a,approval=a.workflow.some(n=>n.type==='human');i.task={input,status:approval?'review':'completed',output:'【固定流程演示，未调用模型或业务工具】\n已载入：'+a.name+' v'+a.version+'\n'+a.workflow.map((n,j)=>(j+1)+'. '+n.title).join('\n')+(approval?'\n\n流程停在人工确认节点。请核对输入后继续。':'\n\n演示流程完成；没有生成真实业务结论。')};i.logs.push({time:now(),text:approval?'演示任务等待人工确认':'演示任务完成'});save();render();}
   if(act==='approve-task'){const i=db.instances.find(i=>i.id===el.dataset.id);if(i.status!=='running'||i.task?.status!=='review')throw Error('当前实例或任务状态不允许确认');i.task.status='completed';i.task.output+='\n\n人工确认通过，演示流程完成。真实分析与文档生成尚未接入。';i.logs.push({time:now(),text:'人工确认演示通过，任务完成'});save();render();}
 }

 const resourceNames={skills:'Skill',workflows:'Workflow',mcp:'MCP',knowledge:'RAG 知识库',tools:'Tool'};
 const resourceDescriptions={skills:'通用专业能力，以版本化 Skill 供智能体选择。',workflows:'可复用的业务步骤与人工确认节点。',mcp:'外部系统连接能力，现场绑定实际连接。',knowledge:'通用资料与项目现场知识检索要求。',tools:'标准工具契约，现场绑定受控适配器。'};
 function libraryPage(){const g=state.libraryGroup,list=db.library[g];return `${header('能力资源管理','统一维护通用能力，在新建和编辑智能体时选择使用。',btn(icon('plus')+'新增 '+resourceNames[g],'resource-new','primary',`data-group="${g}"`))}<div class="panel" style="margin-bottom:23px"><div class="tabs">${Object.entries(resourceNames).map(([id,n])=>btn(n+` <span class="count">${db.library[id].length}</span>`,'library-tab','tab '+(g===id?'active':''),`data-group="${id}"`)).join('')}</div></div><p class="editor-note">${resourceDescriptions[g]} 下方预置资源均为 Mock，不连接真实系统。</p><div class="resource-grid">${list.map(r=>`<section class="panel resource-card"><div class="panel-body"><div class="package-meta"><span class="agent-icon">${icon(g==='workflows'?'studio':g==='tools'?'settings':'file')}</span>${label(r.active===false?'已停用':'Mock 资源',r.active===false?'gray':'')}</div><h3>${h(r.name)}</h3><p>${h(r.description||'可复用能力资源')}</p><div class="heading-meta"><span class="version-tag">v${h(r.version)}</span><span>${h(r.id)}</span></div></div><div class="config-bottom">${btn('编辑资源','resource-edit','small',`data-group="${g}" data-id="${h(r.id)}"`)}${btn(r.active===false?'启用':'停用','resource-toggle','small',`data-group="${g}" data-id="${h(r.id)}"`)}</div></section>`).join('')}</div><div class="center-layout-note" style="margin-top:22px">选择时记录资源版本并复制配置快照。资源库修改不会静默改变已创建智能体；需要更新时，在参数配置中重新选择。</div>`;}
 function resourcePicker(g){const a=state.draft,list=db.library[g],selected=id=>g==='workflows'?(a.resourceRefs||[]).some(r=>r.group===g&&r.id===id):a[g].some(r=>r.id===id);return `<div class="section-head"><div><h3>从通用 ${resourceNames[g]} 资源中选择</h3><p class="note">${resourceDescriptions[g]}</p></div>${btn('管理通用资源','resource-manager','small',`data-group="${g}"`)}</div>${g==='workflows'?'<div class="banner blue">选择一个通用 Workflow，自动带入该流程依赖的 Skill 和 Tool，可在其他配置页核对。</div>':''}<div class="resource-picker">${list.map(r=>`<label class="resource-option ${selected(r.id)?'selected':''} ${r.active===false?'disabled':''}"><input type="${g==='workflows'?'radio':'checkbox'}" name="resource-${g}" data-resource-group="${g}" data-resource-id="${h(r.id)}" ${selected(r.id)?'checked':''} ${r.active===false&&!selected(r.id)?'disabled':''}><span><strong>${h(r.name)}</strong><small>${h(r.description||'通用资源')}<br>v${h(r.version)} · ${h(r.id)} ${r.active===false?'· 已停用':''}</small></span></label>`).join('')}</div>${g==='workflows'&&a.workflow.length?`<div class="workflow-canvas" style="margin-top:20px">${a.workflow.map(n=>`<div class="flow-node ${n.type}"><span class="node-icon">${icon(n.type==='human'?'check':'settings')}</span><div><strong>${h(n.title)}</strong><small>${h(n.target||'人工确认')}</small></div></div>`).join('')}</div>`:''}<p class="center-skill-note" style="margin-top:18px">已选资源随智能体保存；现场资源只保存依赖要求，不包含实际地址、凭据或客户数据。</p>`;}
 function selectResource(g,id,checked){collectDraft();const r=db.library[g].find(x=>x.id===id);if(!r)throw Error('资源不存在');const a=state.draft;a.resourceRefs=a.resourceRefs||[];
   function add(group,item){if(!item||item.active===false)throw Error('流程依赖不存在或已停用');const ix=a[group].findIndex(x=>x.id===item.id);if(ix>=0)a[group][ix]=C.copy(item);else a[group].push(C.copy(item));a.resourceRefs=a.resourceRefs.filter(x=>!(x.group===group&&x.id===item.id));a.resourceRefs.push({group,id:item.id,version:item.version});}
   if(g==='workflows'){a.workflow=C.copy(r.nodes);a.resourceRefs=a.resourceRefs.filter(x=>x.group!=='workflows');a.resourceRefs.push({group:g,id,version:r.version});r.nodes.forEach(n=>{if(n.type==='skill')add('skills',db.library.skills.find(x=>x.id===n.target));if(n.type==='tool')add('tools',db.library.tools.find(x=>x.id===n.target));});}
   else if(checked)add(g,r);else{a[g]=a[g].filter(x=>x.id!==id);a.resourceRefs=a.resourceRefs.filter(x=>!(x.group===g&&x.id===id));}
   if(g==='mcp')a.secretRefs=a.mcp.length?['PROJECT_CONNECTION_TOKEN']:[];
   state.dirty=true;render();
 }
 function openResource(g,id){const current=db.library[g].find(r=>r.id===id),defaults={skills:{content:'说明此技能的处理方法。'},workflows:{nodes:C.copy(CenterLibrary.workflows[0].nodes)},mcp:{capabilities:['read']},knowledge:{mode:'runtime'},tools:{inputSchema:{type:'object',properties:{}},outputSchema:{type:'object',properties:{}}}};
   state.resourceEditing={group:g,id:id||null};const item=current?C.copy(current):{id:'resource-'+Date.now().toString(36),name:'新的'+resourceNames[g],version:'1.0.0',active:true,description:'填写资源适用范围。',...defaults[g]};
   modal((current?'编辑':'新增')+' '+resourceNames[g],`<p class="editor-note">通用 Mock 资源，修改后不会自动影响已创建智能体的配置快照。</p><label class="field">资源定义<textarea id="resource-json" class="code">${h(C.json(item))}</textarea></label>`,btn('保存资源','save-resource','primary'));
 }
 function saveResource(){const {group:g,id}=state.resourceEditing;const r=JSON.parse($('#resource-json').value);if(!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(r.id)||typeof r.name!=='string'||!r.name.trim()||!/^\d+\.\d+\.\d+$/.test(r.version))throw Error('资源标识、名称或版本无效');if(id&&r.id!==id)throw Error('编辑时不能修改资源标识');if(!id&&db.library[g].some(x=>x.id===r.id))throw Error('资源标识重复');if(g==='skills'&&!r.content)throw Error('Skill 内容不能为空');if(g==='workflows'&&(!Array.isArray(r.nodes)||!r.nodes.length))throw Error('Workflow 至少包含一个节点');if(g==='mcp'&&!Array.isArray(r.capabilities))throw Error('MCP 需配置 capabilities');if(g==='knowledge'&&!['package','runtime'].includes(r.mode))throw Error('RAG 类型必须为 package 或 runtime');if(g==='tools'&&(!r.inputSchema||!r.outputSchema))throw Error('Tool 需配置输入输出 Schema');r.active=r.active!==false;if(id)db.library[g]=db.library[g].map(x=>x.id===id?r:x);else db.library[g].push(r);save();$('#modal').close();render();toast('通用资源已保存');}
 document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;if(state.busy)return;Promise.resolve(action(el)).catch(err=>{state.busy=false;toast(err.message);});});
 document.addEventListener('input',e=>{if(e.target.matches('[data-prop],#json-editor,#secret-refs'))state.dirty=true;});
 document.addEventListener('change',async e=>{const el=e.target;
   if(el.id==='project-select')switchProject(el.value);
   if(el.dataset.resourceGroup){try{selectResource(el.dataset.resourceGroup,el.dataset.resourceId,el.checked);}catch(err){toast(err.message);render();}}
   if(el.dataset.bindGroup){const w=state.wizard;if(el.dataset.bindGroup==='root')w.bindings[el.dataset.bindId]=el.value;else w.bindings[el.dataset.bindGroup][el.dataset.bindId]=el.value;}
   if(el.dataset.permission){const b=state.wizard.bindings; b.permissions=b.permissions.filter(p=>p!==el.dataset.permission);if(el.checked)b.permissions.push(el.dataset.permission);}
   if(el.id==='environment-case'){state.wizard.env={compatible:el.value!=='incompatible',network:el.value!=='offline'};}
   if(el.id==='package-file'&&el.files[0]){try{if(el.files[0].size>5*1024*1024)throw Error('原型包超过 5 MB');await importPayload(await el.files[0].text());}catch(err){const target=$('#import-error');if(target){target.hidden=false;target.textContent=err.message;}else toast(err.message);}}
 });
 // 同源父窗口桥接；配置、资源快照与打包核心复用源版本。
 let hostNavigating=false;
 function canLeave(){
  if(state.busy){toast('操作正在完成，请稍后再切换页面');return false;}
  if($('#modal').open){toast('请先保存或关闭当前弹窗，再切换页面');return false;}
  if(state.view==='editor' && state.dirty){
   if(!confirm('当前智能体有未保存的修改。离开将放弃这些修改，是否继续？'))return false;
   state.dirty=false;state.draft=null;state.view='studio';
   hostNavigating=true;render();hostNavigating=false;
  }
  return true;
 }
 window.addEventListener('message',event=>{
  const m=event.data;
  if(event.origin!==location.origin||event.source!==parent||m?.channel!=='fanzha-platform')return;
  if(m.type==='theme' && Number.isFinite(m.fontSize)){
   document.documentElement.style.fontSize=Math.max(10,Math.min(24,m.fontSize))+'px';return;
  }
  if(m.type!=='navigate'&&m.type!=='leave')return;
  const allowed=m.type==='leave'||['studio','library','packages'].includes(m.view);
  const same=m.type==='navigate'&&(state.view==='editor'?'studio':state.view)===m.view;
  const ok=allowed&&(same||canLeave());
  if(ok && m.type==='navigate'&&!same){
   hostNavigating=true;state.view=m.view;state.draft=null;state.dirty=false;
   state.wizard=null;state.wizardStep=0;render();hostNavigating=false;window.scrollTo(0,0);
  }
  parent.postMessage({channel:'fanzha-agent-center',type:'ack',id:m.id,ok,view:state.view==='editor'?'studio':state.view},location.origin);
 });
 window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue='';}});
 render();
 parent.postMessage({channel:'fanzha-agent-center',type:'ready',view:state.view==='editor'?'studio':state.view},location.origin);
})();
