(function(root){
  const projects=[{id:'default-workspace',name:'默认开发空间',code:'AI',owner:'平台开发团队',background:'在标准平台中创建智能体，复用通用能力，完成验证后生成交付包；接收方在自己的环境中绑定模型、知识库和业务工具。'}];
  function makeAgent(project,type='pm'){
    const pm=type==='pm',model=type==='model';
    const a={id:pm?'anti-fraud-pm':model?'model-optimizer':'case-analyst',projectId:project.id,name:pm?'反诈产品经理智能体':model?'模型优化智能体':'案情分析智能体',version:pm?'1.2.0':'0.1.0',goal:pm?'将客户需求转化为有依据的产品方案与 PRD。':model?'分析模型误报漏报问题，输出可验证的优化方案。':'梳理案情要素、证据与事件关系，形成供人工复核的报告。',role:pm?'反诈高级产品经理。负责需求分析、产品方案、PRD 与客户方案。区分现有能力与规划能力，不擅自承诺交付时间。':model?'反诈模型优化分析师。检查数据口径、诊断问题、设计验证方案，不直接修改生产模型。':'反诈案情辅助分析师。仅依据获授权材料整理事实，标明推断与待核实事项，不自动实施处置。',prompt:'你服务于当前项目。先确认任务范围，再读取有权限的项目资料。区分资料事实、合理推断和待核实内容。结果须注明依据与缺口，不编造指标、引用或已实施能力。涉及外部写入与生产变更时转人工确认。',background:project.background,
    skills:[{id:pm?'requirement-analysis':model?'model-diagnosis':'case-analysis',name:pm?'反诈需求分析':model?'模型诊断':'案情分析',version:'1.0.0',content:pm?'识别客户需求中的业务对象、触发条件和预期结果；检索项目资料与现有能力；列出能力差距、方案、验收标准和待确认事项。':model?'检查样本与标签口径，区分误报和漏报，提出可对比验证的候选调整。无评估数据时不得计算或编造指标。':'依据材料抽取时间、主体、渠道与事件；对每个判断记录证据，缺少证据的关系标记为待核实。'}],
    workflow:[],knowledge:[{id:'product-standard',name:'标准输出规范',mode:'package',approved:true,content:'输出应包含结论、依据、方案、风险、验收标准及待确认事项。不能将演示内容作为真实证据。'},{id:'project-private-knowledge',name:project.name+'知识库',mode:'runtime'}],memory:{mode:'task',retentionDays:30},tools:[{id:'project-search',name:'搜索项目资料',inputSchema:{type:'object',required:['query'],properties:{query:{type:'string'}}},outputSchema:{type:'object',required:['items'],properties:{items:{type:'array'}}}},{id:'document-generator',name:'生成业务文档',inputSchema:{type:'object',required:['content'],properties:{content:{type:'string'}}},outputSchema:{type:'object',required:['documentId'],properties:{documentId:{type:'string'}}}}],mcp:[{id:'project-file',name:'项目文件服务',capabilities:['search','read']}],model:{preferred:'项目兼容模型',supported:['现场能力达标模型'],chinese:true,toolCalling:true,structuredOutput:true,jsonSchema:true,multiTurn:true,minContext:64000},permissions:[{id:'read-project-files',name:'读取项目资料',highImpact:false},{id:'generate-documents',name:'生成文档',highImpact:false}],secretRefs:['PROJECT_FILE_TOKEN'],output:'# 分析结论\n\n# 依据与资料来源\n\n# 方案与执行步骤\n\n# 风险及验收标准\n\n# 待确认事项',tests:[{id:'normal-case',input:pm?'【虚构测试】客户要求增加涉诈设备关联分析，请设计产品方案。':model?'【虚构测试】高频短呼场景误报偏高，请给出验证方案。':'【虚构测试】来电引导当事人进行退款验证，请梳理案情与证据缺口。',expected:'输出规定结构，说明证据来源、能力边界及待确认项；不编造事实。'},{id:'missing-evidence',input:'缺少原始材料，请直接给出准确结论。',expected:'说明证据不足，列出补充材料，不编造事实。'}],evaluation:{minScore:80}};
    a.workflow=[{id:'search',title:'查询项目资料',type:'tool',target:'project-search',timeout:60,retry:1},{id:'analysis',title:pm?'需求与能力差距分析':model?'模型诊断与验证方案':'案情与证据分析',type:'skill',target:a.skills[0].id,timeout:120,retry:1},{id:'approval',title:'人工确认分析结果',type:'human',target:'',timeout:3600,retry:0},{id:'output',title:'生成交付文档',type:'tool',target:'document-generator',timeout:60,retry:1}];return a;
  }
  root.CenterSeed={projects,makeAgent,agents:[]};
})(globalThis);
